// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/migege/anthill/proto/log/log.proto

/*
Package migege_anthill_log is a generated protocol buffer package.

It is generated from these files:
	github.com/migege/anthill/proto/log/log.proto

It has these top-level messages:
	Info
*/
package migege_anthill_log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Info struct {
	Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Ts   int64  `protobuf:"varint,2,opt,name=ts" json:"ts,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Info) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Info) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func init() {
	proto.RegisterType((*Info)(nil), "migege.anthill.log.Info")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Logger service

type LoggerClient interface {
	Log(ctx context.Context, in *Info, opts ...client.CallOption) (*Info, error)
	LogStatus(ctx context.Context, in *Info, opts ...client.CallOption) (*Info, error)
	GetStatus(ctx context.Context, in *Info, opts ...client.CallOption) (*Info, error)
}

type loggerClient struct {
	c           client.Client
	serviceName string
}

func NewLoggerClient(serviceName string, c client.Client) LoggerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "migege.anthill.log"
	}
	return &loggerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *loggerClient) Log(ctx context.Context, in *Info, opts ...client.CallOption) (*Info, error) {
	req := c.c.NewRequest(c.serviceName, "Logger.Log", in)
	out := new(Info)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogStatus(ctx context.Context, in *Info, opts ...client.CallOption) (*Info, error) {
	req := c.c.NewRequest(c.serviceName, "Logger.LogStatus", in)
	out := new(Info)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) GetStatus(ctx context.Context, in *Info, opts ...client.CallOption) (*Info, error) {
	req := c.c.NewRequest(c.serviceName, "Logger.GetStatus", in)
	out := new(Info)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Logger service

type LoggerHandler interface {
	Log(context.Context, *Info, *Info) error
	LogStatus(context.Context, *Info, *Info) error
	GetStatus(context.Context, *Info, *Info) error
}

func RegisterLoggerHandler(s server.Server, hdlr LoggerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Logger{hdlr}, opts...))
}

type Logger struct {
	LoggerHandler
}

func (h *Logger) Log(ctx context.Context, in *Info, out *Info) error {
	return h.LoggerHandler.Log(ctx, in, out)
}

func (h *Logger) LogStatus(ctx context.Context, in *Info, out *Info) error {
	return h.LoggerHandler.LogStatus(ctx, in, out)
}

func (h *Logger) GetStatus(ctx context.Context, in *Info, out *Info) error {
	return h.LoggerHandler.GetStatus(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/migege/anthill/proto/log/log.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0x4f, 0x4d, 0x4f, 0xd5, 0x4f, 0xcc,
	0x2b, 0xc9, 0xc8, 0xcc, 0xc9, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0xc9, 0x4f, 0x07,
	0x61, 0x3d, 0x30, 0x4f, 0x48, 0x08, 0xa2, 0x46, 0x0f, 0xaa, 0x46, 0x2f, 0x27, 0x3f, 0x5d, 0x49,
	0x8b, 0x8b, 0xc5, 0x33, 0x2f, 0x2d, 0x5f, 0x48, 0x88, 0x8b, 0x25, 0x33, 0x2f, 0x2d, 0x5f, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0xe2, 0xe3, 0x62, 0x2a, 0x29, 0x96, 0x60, 0x52,
	0x60, 0xd4, 0x60, 0x0e, 0x62, 0x2a, 0x29, 0x36, 0x3a, 0xcd, 0xc8, 0xc5, 0xe6, 0x93, 0x9f, 0x9e,
	0x9e, 0x5a, 0x24, 0x64, 0xcd, 0xc5, 0xec, 0x93, 0x9f, 0x2e, 0x24, 0xa1, 0x87, 0x69, 0xa4, 0x1e,
	0xc8, 0x3c, 0x29, 0x9c, 0x32, 0x4a, 0x0c, 0x42, 0x8e, 0x5c, 0x9c, 0x3e, 0xf9, 0xe9, 0xc1, 0x25,
	0x89, 0x25, 0xa5, 0xc5, 0xe4, 0x1b, 0xe1, 0x9e, 0x5a, 0x42, 0x89, 0x11, 0x49, 0x6c, 0xe0, 0x40,
	0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x78, 0xb3, 0x22, 0x3c, 0x45, 0x01, 0x00, 0x00,
}
