// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/migege/anthill/proto/user/user.proto

/*
Package migege_anthill_user is a generated protocol buffer package.

It is generated from these files:
	github.com/migege/anthill/proto/user/user.proto

It has these top-level messages:
	User
	Account
*/
package migege_anthill_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Account struct {
	User     *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	TsExpire int64 `protobuf:"varint,2,opt,name=ts_expire,json=tsExpire" json:"ts_expire,omitempty"`
	Frozen   bool  `protobuf:"varint,3,opt,name=frozen" json:"frozen,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Account) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Account) GetTsExpire() int64 {
	if m != nil {
		return m.TsExpire
	}
	return 0
}

func (m *Account) GetFrozen() bool {
	if m != nil {
		return m.Frozen
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "migege.anthill.user.User")
	proto.RegisterType((*Account)(nil), "migege.anthill.user.Account")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	Register(ctx context.Context, in *User, opts ...client.CallOption) (*Account, error)
	Login(ctx context.Context, in *User, opts ...client.CallOption) (*Account, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "migege.anthill.user"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) Register(ctx context.Context, in *User, opts ...client.CallOption) (*Account, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Register", in)
	out := new(Account)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *User, opts ...client.CallOption) (*Account, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Login", in)
	out := new(Account)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Register(context.Context, *User, *Account) error
	Login(context.Context, *User, *Account) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) Register(ctx context.Context, in *User, out *Account) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *UserService) Login(ctx context.Context, in *User, out *Account) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/migege/anthill/proto/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xbd, 0x4e, 0xc4, 0x30,
	0x10, 0x84, 0x09, 0xf7, 0x43, 0x6e, 0xaf, 0x5b, 0x10, 0x0a, 0x07, 0x05, 0x4a, 0x45, 0x83, 0x2d,
	0x1d, 0x4f, 0x00, 0xd2, 0x75, 0x54, 0x06, 0x6a, 0x94, 0x0b, 0x8b, 0x63, 0xe9, 0x62, 0x47, 0xb6,
	0x03, 0x88, 0x27, 0xe1, 0x71, 0x91, 0x37, 0x81, 0xea, 0xa8, 0x68, 0x2c, 0x7d, 0x9a, 0xf1, 0xcc,
	0x68, 0x41, 0x6a, 0x13, 0x9b, 0x7e, 0x2b, 0x6a, 0xd7, 0xca, 0xd6, 0x68, 0xd2, 0x24, 0x2b, 0x1b,
	0x1b, 0xb3, 0xdb, 0xc9, 0xce, 0xbb, 0xe8, 0x64, 0x1f, 0xc8, 0xf3, 0x23, 0x98, 0xf1, 0x78, 0x70,
	0x89, 0xd1, 0x25, 0x92, 0x54, 0x3e, 0xc2, 0xf4, 0x29, 0x90, 0xc7, 0x13, 0x98, 0x75, 0x8d, 0xb3,
	0x54, 0x64, 0x97, 0xd9, 0xd5, 0x42, 0x0d, 0x80, 0x2b, 0xc8, 0x93, 0xcb, 0x56, 0x2d, 0x15, 0x87,
	0x2c, 0xfc, 0x72, 0xd2, 0xba, 0x2a, 0x84, 0x77, 0xe7, 0x5f, 0x8a, 0xc9, 0xa0, 0xfd, 0x70, 0xd9,
	0xc2, 0xd1, 0x6d, 0x5d, 0xbb, 0xde, 0x46, 0xbc, 0x86, 0x69, 0xfa, 0xc2, 0xb9, 0xcb, 0xf5, 0x99,
	0xd8, 0x33, 0x42, 0xa4, 0x05, 0x8a, 0x6d, 0x78, 0x0e, 0x8b, 0x18, 0x9e, 0xe9, 0xa3, 0x33, 0x7e,
	0xa8, 0x9c, 0xa8, 0x3c, 0x86, 0x0d, 0x33, 0x9e, 0xc2, 0xfc, 0xd5, 0xbb, 0x4f, 0xb2, 0x5c, 0x98,
	0xab, 0x91, 0xd6, 0x5f, 0x19, 0x2c, 0x53, 0xc6, 0x03, 0xf9, 0x37, 0x53, 0x13, 0x6e, 0x20, 0x57,
	0xa4, 0x4d, 0x88, 0xe4, 0xf1, 0xef, 0xc6, 0xd5, 0xc5, 0x5e, 0x69, 0x1c, 0x5e, 0x1e, 0xe0, 0x1d,
	0xcc, 0xee, 0x9d, 0x36, 0xf6, 0x1f, 0x19, 0xdb, 0x39, 0xdf, 0xfe, 0xe6, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x3c, 0x3e, 0x86, 0xf2, 0xae, 0x01, 0x00, 0x00,
}
